// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0rWfyHQyZknUdxeS90BBIxwx95kTsBz0',
    appId: '1:835844393002:web:4a31f62bd27cf8e46d5b53',
    messagingSenderId: '835844393002',
    projectId: 'fir-auth-c8a89',
    authDomain: 'fir-auth-c8a89.firebaseapp.com',
    storageBucket: 'fir-auth-c8a89.firebasestorage.app',
    measurementId: 'G-8CWC0K1KF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6t-ayt5yeEgGpYZU9h0hsdnUbhDCvZ9w',
    appId: '1:835844393002:android:e6ca755f5edcda296d5b53',
    messagingSenderId: '835844393002',
    projectId: 'fir-auth-c8a89',
    storageBucket: 'fir-auth-c8a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSBnebKeN_sFkv-E44oZPZtPSsoaukW4',
    appId: '1:835844393002:ios:c5958a02a11ba8186d5b53',
    messagingSenderId: '835844393002',
    projectId: 'fir-auth-c8a89',
    storageBucket: 'fir-auth-c8a89.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFSBnebKeN_sFkv-E44oZPZtPSsoaukW4',
    appId: '1:835844393002:ios:c5958a02a11ba8186d5b53',
    messagingSenderId: '835844393002',
    projectId: 'fir-auth-c8a89',
    storageBucket: 'fir-auth-c8a89.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0rWfyHQyZknUdxeS90BBIxwx95kTsBz0',
    appId: '1:835844393002:web:6ccf7d4b7f8ef3806d5b53',
    messagingSenderId: '835844393002',
    projectId: 'fir-auth-c8a89',
    authDomain: 'fir-auth-c8a89.firebaseapp.com',
    storageBucket: 'fir-auth-c8a89.firebasestorage.app',
    measurementId: 'G-H01DG0KBL7',
  );
}
